"""Verified inference settings for the five demo checkpoints."""
from copy import deepcopy

_SETTINGS = {'dinov2_unetpp': {'config': {'num_labels': 13,
                              'backbone_config': {'hidden_size': 1024,
                                                  'num_hidden_layers': 24,
                                                  'num_attention_heads': 16,
                                                  'image_size': 518,
                                                  'out_features': ['stage24'],
                                                  'out_indices': [24],
                                                  'output_hidden_states': True},
                              'decoder_config': {'decoder_channels': 256, 'use_attention': True}},
                   'preprocessing': {'size': [768, 768],
                                     'image_mean': [0.485, 0.456, 0.406],
                                     'image_std': [0.229, 0.224, 0.225]}},
 'oneformer': {'config': {'num_labels': 12,
                          'num_queries': 250,
                          'contrastive_weight': 0.0,
                          'output_hidden_states': True,
                          'output_attentions': True,
                          'backbone_config': {'model_type': 'swin',
                                              'image_size': 384,
                                              'embed_dim': 192,
                                              'depths': [2, 2, 18, 2],
                                              'num_heads': [6, 12, 24, 48],
                                              'window_size': 12,
                                              'drop_path_rate': 0.3,
                                              'out_features': ['stage1',
                                                               'stage2',
                                                               'stage3',
                                                               'stage4'],
                                              'out_indices': [1, 2, 3, 4]}},
               'preprocessing': {'size': [768, 768], 'image_mean': None, 'image_std': None}},
 'thinhrnet_ocr': {'config': {'num_labels': 13,
                              'model_kwargs': {'backbone_name': 'hrnet_w48',
                                               'num_classes': 13,
                                               'use_pointrend': False,
                                               'pointrend_points': 4096,
                                               'pointrend_topk_ratio': 0.75}},
                   'preprocessing': {'size': [512, 512],
                                     'image_mean': [0.485, 0.456, 0.406],
                                     'image_std': [0.229, 0.224, 0.225]}},
 'afs': {'config': {'num_labels': 12},
         'preprocessing': {'size': [1024, 1024],
                           'image_mean': [0.485, 0.456, 0.406],
                           'image_std': [0.229, 0.224, 0.225]}},
 'mask2former': {'config': {'num_labels': 12,
                            'backbone_config': {'model_type': 'swin',
                                                'image_size': 384,
                                                'embed_dim': 192,
                                                'depths': [2, 2, 18, 2],
                                                'num_heads': [6, 12, 24, 48],
                                                'window_size': 12,
                                                'drop_path_rate': 0.3,
                                                'out_features': ['stage1',
                                                                 'stage2',
                                                                 'stage3',
                                                                 'stage4'],
                                                'out_indices': [1, 2, 3, 4]}},
                 'preprocessing': {'size': [768, 768],
                                   'image_mean': [0.485, 0.456, 0.406],
                                   'image_std': [0.229, 0.224, 0.225]}}}

_SETTINGS["oneformer"]["task_input_ids"] = [49406, 518, 10549, 533, 29119, 1550] + [49407] * 71

def get_settings(model_type):
    return deepcopy(_SETTINGS[model_type])
